version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: derrickwoo/dockertest
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Login Dockerhub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Push Docker Image
          command: docker push derrickwoo/dockertest:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
only: master
